### ISSUE TITLE
executions for some cells (before sampling) take ~ min

### ISSUE THREAD

**Issue by avivajpeyi** [dfm/tess-atlas#149]
Although building the model is quick ~1s, running the `test_model` function takes ~ 1min. 

<img width="1346" alt="Screen Shot 2021-11-19 at 3 17 26 pm" src="https://user-images.githubusercontent.com/15642823/142564116-94db8a9e-bdde-4e26-95d4-151601622209.png">

For ref: 
```python

def test_model(model):
    """Test a point in the model and assure no nans"""
    with model:
        test_prob = model.check_test_point()
        test_prob.name = "log P(test-point)"
        if test_prob.isnull().values.any():
            raise ValueError(f"The model(testval) has a nan:\n{test_prob}")
        test_pt = pd.Series(
            {
                k: str(round(np.array(v).flatten()[0], 2))
                for k, v in model.test_point.items()
            },
            name="Test Point",
        )
        return pd.concat([test_pt, test_prob], axis=1)

```

Similarly, optimizing the initial params takes ~3min: 
<img width="971" alt="Screen Shot 2021-11-19 at 3 23 19 pm" src="https://user-images.githubusercontent.com/15642823/142564594-f591a949-a156-4ee4-a4b3-f2205989dcce.png">

I understand that the optimization can take some time, but don't understand why the `test_model` takes ~1min...

**Comment by dfm** [comment]
This happens because Theano needs to compile the model when it is first used. These compiled models are (generally) cached and re-used, but since we're setting our "compiledir", each process will take some overhead to compile the first time. I'm not sure that there's really anything to do about this. I've tried some "clever" things in the past to share the cache between processes, but this always ends up being more trouble than it is worth!

**Comment by avivajpeyi** [comment]
Ah ok! Thanks Dan
